#ifndef CMD_H
#define CMD_H

#define MF_CLASSIC_CMD_AUTH_KEY_A          (0x60U)
#define MF_CLASSIC_CMD_AUTH_KEY_B          (0x61U)
#define MF_CLASSIC_CMD_BACKDOOR_AUTH_KEY_A (0x64U)
#define MF_CLASSIC_CMD_BACKDOOR_AUTH_KEY_B (0x65U)
#define MF_CLASSIC_CMD_READ_BLOCK          (0x30U)
#define MF_CLASSIC_CMD_WRITE_BLOCK         (0xA0U)
#define MF_CLASSIC_CMD_VALUE_DEC           (0xC0U)
#define MF_CLASSIC_CMD_VALUE_INC           (0xC1U)
#define MF_CLASSIC_CMD_VALUE_RESTORE       (0xC2U)
#define MF_CLASSIC_CMD_VALUE_TRANSFER      (0xB0U)

#define MF_CLASSIC_CMD_HALT_MSB                (0x50)
#define MF_CLASSIC_CMD_HALT_LSB                (0x00)
#define MF_CLASSIC_CMD_ACK                     (0x0A)
#define MF_CLASSIC_CMD_NACK                    (0x00)
#define MF_CLASSIC_CMD_NACK_TRANSFER_INVALID   (0x04)
#define MF_CLASSIC_CMD_NACK_TRANSFER_CRC_ERROR (0x01)

#define MF_CLASSIC_TOTAL_SECTORS_MAX (40)
#define MF_CLASSIC_TOTAL_BLOCKS_MAX  (256)
#define MF_CLASSIC_READ_MASK_SIZE    (MF_CLASSIC_TOTAL_BLOCKS_MAX / 32)
#define MF_CLASSIC_BLOCK_SIZE        (16)
#define MF_CLASSIC_KEY_SIZE          (6)
#define MF_CLASSIC_ACCESS_BYTES_SIZE (4)

#define MF_CLASSIC_NT_SIZE (4)
#define MF_CLASSIC_NR_SIZE (4)
#define MF_CLASSIC_AR_SIZE (4)
#define MF_CLASSIC_AT_SIZE (4)

#define MF_DESFIRE_CMD_GET_VERSION         (0x60)
#define MF_DESFIRE_CMD_GET_FREE_MEMORY     (0x6E)
#define MF_DESFIRE_CMD_GET_KEY_SETTINGS    (0x45)
#define MF_DESFIRE_CMD_GET_KEY_VERSION     (0x64)
#define MF_DESFIRE_CMD_GET_APPLICATION_IDS (0x6A)
#define MF_DESFIRE_CMD_SELECT_APPLICATION  (0x5A)
#define MF_DESFIRE_CMD_GET_FILE_IDS        (0x6F)
#define MF_DESFIRE_CMD_GET_FILE_SETTINGS   (0xF5)

#define MF_DESFIRE_CMD_READ_DATA    (0xBD)
#define MF_DESFIRE_CMD_GET_VALUE    (0x6C)
#define MF_DESFIRE_CMD_READ_RECORDS (0xBB)

#define MF_DESFIRE_MAX_KEYS  (14)
#define MF_DESFIRE_MAX_FILES (32)

#define MF_DESFIRE_UID_SIZE    (7)
#define MF_DESFIRE_BATCH_SIZE  (5)
#define MF_DESFIRE_APP_ID_SIZE (3)
#define MF_DESFIRE_VALUE_SIZE  (4)

#define MF_ULTRALIGHT_TEARING_FLAG_DEFAULT (0xBD)

#define MF_ULTRALIGHT_CMD_GET_VERSION   (0x60)
#define MF_ULTRALIGHT_CMD_READ_PAGE     (0x30)
#define MF_ULTRALIGHT_CMD_FAST_READ     (0x3A)
#define MF_ULTRALIGHT_CMD_SECTOR_SELECT (0xC2)
#define MF_ULTRALIGHT_CMD_COMP_WRITE    (0xA0)
#define MF_ULTRALIGHT_CMD_WRITE_PAGE    (0xA2)
#define MF_ULTRALIGHT_CMD_FAST_WRITE    (0xA6)
#define MF_ULTRALIGHT_CMD_READ_SIG      (0x3C)
#define MF_ULTRALIGHT_CMD_READ_CNT      (0x39)
#define MF_ULTRALIGHT_CMD_INCR_CNT      (0xA5)
#define MF_ULTRALIGHT_CMD_CHECK_TEARING (0x3E)
#define MF_ULTRALIGHT_CMD_PWD_AUTH      (0x1B)
#define MF_ULTRALIGHT_CMD_AUTH          (0x1A)
#define MF_ULTRALIGHT_CMD_VCSL          (0x4B)

#define MF_ULTRALIGHT_CMD_ACK      (0x0A)
#define MF_ULTRALIGHT_CMD_NACK     (0x00)
#define MF_ULTRALIGHT_CMD_AUTH_NAK (0x04)

#define MF_ULTRALIGHT_MAX_CNTR_VAL       (0x00FFFFFF)
#define MF_ULTRALIGHT_MAX_PAGE_NUM       (510)
#define MF_ULTRALIGHT_PAGE_SIZE          (4U)
#define MF_ULTRALIGHT_SIGNATURE_SIZE     (32)
#define MF_ULTRALIGHT_COUNTER_SIZE       (3)
#define MF_ULTRALIGHT_COUNTER_NUM        (3)
#define MF_ULTRALIGHT_TEARING_FLAG_SIZE  (1)
#define MF_ULTRALIGHT_TEARING_FLAG_NUM   (3)
#define MF_ULTRALIGHT_AUTH_PASSWORD_SIZE (4)
#define MF_ULTRALIGHT_AUTH_PACK_SIZE     (2)

#define MF_ULTRALIGHT_C_AUTH_RESPONSE_SIZE      (9)
#define MF_ULTRALIGHT_C_AUTH_DES_KEY_SIZE       (16)
#define MF_ULTRALIGHT_C_AUTH_DATA_SIZE          (MF_ULTRALIGHT_C_AUTH_DES_KEY_SIZE)
#define MF_ULTRALIGHT_C_AUTH_IV_BLOCK_SIZE      (8)
#define MF_ULTRALIGHT_C_AUTH_RND_BLOCK_SIZE     (8)
#define MF_ULTRALIGHT_C_AUTH_RND_A_BLOCK_OFFSET (0)
#define MF_ULTRALIGHT_C_AUTH_RND_B_BLOCK_OFFSET (8)
#define MF_ULTRALIGHT_C_ENCRYPTED_PACK_SIZE     (MF_ULTRALIGHT_C_AUTH_DATA_SIZE + 1)

#define SLIX_BLOCK_SIZE     (4U)
#define SLIX_SIGNATURE_SIZE (32U)

#define SLIX_COUNTER_BLOCK_NUM (79U)

#define SLIX_PP_CONDITION_RL (1U << 0)
#define SLIX_PP_CONDITION_WL (1U << 1)
#define SLIX_PP_CONDITION_RH (1U << 4)
#define SLIX_PP_CONDITION_WH (1U << 5)

#define SLIX_FEATURE_FLAG_UM_PP              (1UL << 0)
#define SLIX_FEATURE_FLAG_COUNTER            (1UL << 1)
#define SLIX_FEATURE_FLAG_EAS_ID             (1UL << 2)
#define SLIX_FEATURE_FLAG_EAS_PP             (1UL << 3)
#define SLIX_FEATURE_FLAG_AFI_PP             (1UL << 4)
#define SLIX_FEATURE_FLAG_INVENTORY_READ_EXT (1UL << 5)
#define SLIX_FEATURE_FLAG_EAS_IR             (1UL << 6)
#define SLIX_FEATURE_FLAG_ORIGINALITY_SIG    (1UL << 8)
#define SLIX_FEATURE_FLAG_ORIGINALITY_SIG_PP (1UL << 9)
#define SLIX_FEATURE_FLAG_PERSISTENT_QUIET   (1UL << 10)
#define SLIX_FEATURE_FLAG_PRIVACY            (1UL << 12)
#define SLIX_FEATURE_FLAG_DESTROY            (1UL << 13)
#define SLIX_FEATURE_EXT                     (1UL << 31)

#define SLIX_TYPE_FEATURE_READ            (1U << 0)
#define SLIX_TYPE_FEATURE_WRITE           (1U << 1)
#define SLIX_TYPE_FEATURE_PRIVACY         (1U << 2)
#define SLIX_TYPE_FEATURE_DESTROY         (1U << 3)
#define SLIX_TYPE_FEATURE_EAS             (1U << 4)
#define SLIX_TYPE_FEATURE_SIGNATURE       (1U << 5)
#define SLIX_TYPE_FEATURE_PROTECTION      (1U << 6)
#define SLIX_TYPE_FEATURE_NFC_SYSTEM_INFO (1U << 7)

#define ISO15693_3_UID_SIZE (8U)

#define ISO15693_3_GUARD_TIME_US    (5000U)
#define ISO15693_3_FDT_POLL_FC      (4202U)
#define ISO15693_3_FDT_LISTEN_FC    (4320U)
#define ISO15693_3_POLL_POLL_MIN_US (1500U)

#define ISO15693_3_REQ_FLAG_SUBCARRIER_1 (0U << 0)
#define ISO15693_3_REQ_FLAG_SUBCARRIER_2 (1U << 0)
#define ISO15693_3_REQ_FLAG_DATA_RATE_LO (0U << 1)
#define ISO15693_3_REQ_FLAG_DATA_RATE_HI (1U << 1)
#define ISO15693_3_REQ_FLAG_INVENTORY_T4 (0U << 2)
#define ISO15693_3_REQ_FLAG_INVENTORY_T5 (1U << 2)
#define ISO15693_3_REQ_FLAG_EXTENSION    (1U << 3)

#define ISO15693_3_REQ_FLAG_T4_SELECTED  (1U << 4)
#define ISO15693_3_REQ_FLAG_T4_ADDRESSED (1U << 5)
#define ISO15693_3_REQ_FLAG_T4_OPTION    (1U << 6)

#define ISO15693_3_REQ_FLAG_T5_AFI_PRESENT (1U << 4)
#define ISO15693_3_REQ_FLAG_T5_N_SLOTS_16  (0U << 5)
#define ISO15693_3_REQ_FLAG_T5_N_SLOTS_1   (1U << 5)
#define ISO15693_3_REQ_FLAG_T5_OPTION      (1U << 6)

#define ISO15693_3_RESP_FLAG_NONE      (0U)
#define ISO15693_3_RESP_FLAG_ERROR     (1U << 0)
#define ISO15693_3_RESP_FLAG_EXTENSION (1U << 3)

#define ISO15693_3_RESP_ERROR_NOT_SUPPORTED        (0x01U)
#define ISO15693_3_RESP_ERROR_FORMAT               (0x02U)
#define ISO15693_3_RESP_ERROR_OPTION               (0x03U)
#define ISO15693_3_RESP_ERROR_UNKNOWN              (0x0FU)
#define ISO15693_3_RESP_ERROR_BLOCK_UNAVAILABLE    (0x10U)
#define ISO15693_3_RESP_ERROR_BLOCK_ALREADY_LOCKED (0x11U)
#define ISO15693_3_RESP_ERROR_BLOCK_LOCKED         (0x12U)
#define ISO15693_3_RESP_ERROR_BLOCK_WRITE          (0x13U)
#define ISO15693_3_RESP_ERROR_BLOCK_LOCK           (0x14U)
#define ISO15693_3_RESP_ERROR_CUSTOM_START         (0xA0U)
#define ISO15693_3_RESP_ERROR_CUSTOM_END           (0xDFU)

#define ISO15693_3_CMD_MANDATORY_START     (0x01U)
#define ISO15693_3_CMD_INVENTORY           (0x01U)
#define ISO15693_3_CMD_STAY_QUIET          (0x02U)
#define ISO15693_3_CMD_MANDATORY_RFU       (0x03U)
#define ISO15693_3_CMD_OPTIONAL_START      (0x20U)
#define ISO15693_3_CMD_READ_BLOCK          (0x20U)
#define ISO15693_3_CMD_WRITE_BLOCK         (0x21U)
#define ISO15693_3_CMD_LOCK_BLOCK          (0x22U)
#define ISO15693_3_CMD_READ_MULTI_BLOCKS   (0x23U)
#define ISO15693_3_CMD_WRITE_MULTI_BLOCKS  (0x24U)
#define ISO15693_3_CMD_SELECT              (0x25U)
#define ISO15693_3_CMD_RESET_TO_READY      (0x26U)
#define ISO15693_3_CMD_WRITE_AFI           (0x27U)
#define ISO15693_3_CMD_LOCK_AFI            (0x28U)
#define ISO15693_3_CMD_WRITE_DSFID         (0x29U)
#define ISO15693_3_CMD_LOCK_DSFID          (0x2AU)
#define ISO15693_3_CMD_GET_SYS_INFO        (0x2BU)
#define ISO15693_3_CMD_GET_BLOCKS_SECURITY (0x2CU)
#define ISO15693_3_CMD_OPTIONAL_RFU        (0x2DU)
#define ISO15693_3_CMD_CUSTOM_START        (0xA0U)

#define ISO15693_3_MANDATORY_COUNT (ISO15693_3_CMD_MANDATORY_RFU - ISO15693_3_CMD_MANDATORY_START)
#define ISO15693_3_OPTIONAL_COUNT  (ISO15693_3_CMD_OPTIONAL_RFU - ISO15693_3_CMD_OPTIONAL_START)

#define ISO15693_3_SYSINFO_FLAG_DSFID  (1U << 0)
#define ISO15693_3_SYSINFO_FLAG_AFI    (1U << 1)
#define ISO15693_3_SYSINFO_FLAG_MEMORY (1U << 2)
#define ISO15693_3_SYSINFO_FLAG_IC_REF (1U << 3)

#define ISO14443_3A_UID_4_BYTES  (4U)
#define ISO14443_3A_UID_7_BYTES  (7U)
#define ISO14443_3A_UID_10_BYTES (10U)
#define ISO14443_3A_MAX_UID_SIZE ISO14443_3A_UID_10_BYTES

#define ISO14443_3A_GUARD_TIME_US     (5000)
#define ISO14443_3A_FDT_POLL_FC       (1620)
#define ISO14443_3A_FDT_LISTEN_FC     (1172)
#define ISO14443_3A_POLLER_MASK_RX_FS ((ISO14443_3A_FDT_LISTEN_FC) / 2)
#define ISO14443_3A_POLL_POLL_MIN_US  (1100)

#define FELICA_IDM_SIZE        (8U)
#define FELICA_PMM_SIZE        (8U)
#define FELICA_DATA_BLOCK_SIZE (16U)

#define FELICA_CMD_READ_WITHOUT_ENCRYPTION  (0x06U)
#define FELICA_CMD_WRITE_WITHOUT_ENCRYPTION (0x08U)

#define FELICA_SERVICE_RW_ACCESS (0x0009U)
#define FELICA_SERVICE_RO_ACCESS (0x000BU)

#define FELICA_BLOCKS_TOTAL_COUNT    (28U)
#define FELICA_BLOCK_INDEX_REG       (0x0EU)
#define FELICA_BLOCK_INDEX_RC        (0x80U)
#define FELICA_BLOCK_INDEX_MAC       (0x81U)
#define FELICA_BLOCK_INDEX_ID        (0x82U)
#define FELICA_BLOCK_INDEX_D_ID      (0x83U)
#define FELICA_BLOCK_INDEX_SER_C     (0x84U)
#define FELICA_BLOCK_INDEX_SYS_C     (0x85U)
#define FELICA_BLOCK_INDEX_CKV       (0x86U)
#define FELICA_BLOCK_INDEX_CK        (0x87U)
#define FELICA_BLOCK_INDEX_MC        (0x88U)
#define FELICA_BLOCK_INDEX_WCNT      (0x90U)
#define FELICA_BLOCK_INDEX_MAC_A     (0x91U)
#define FELICA_BLOCK_INDEX_STATE     (0x92U)
#define FELICA_BLOCK_INDEX_CRC_CHECK (0xA0U)

#define FELICA_GUARD_TIME_US    (20000U)
#define FELICA_FDT_POLL_FC      (10000U)
#define FELICA_POLL_POLL_MIN_US (1280U)

#define FELICA_FDT_LISTEN_FC (1172)

#define FELICA_SYSTEM_CODE_CODE (0xFFFFU)
#define FELICA_TIME_SLOT_1      (0x00U)
#define FELICA_TIME_SLOT_2      (0x01U)
#define FELICA_TIME_SLOT_4      (0x03U)
#define FELICA_TIME_SLOT_8      (0x07U)
#define FELICA_TIME_SLOT_16     (0x0FU)

#define MAX_APDU_LEN 255

#define EMV_REQ_GET_DATA 0x80CA

#define UNKNOWN_TAG 0x0B

#define EMV_TAG_AID                      0x4F
#define EMV_TAG_PRIORITY                 0x87
#define EMV_TAG_APPL_INTERCHANGE_PROFILE 0x82
#define EMV_TAG_PDOL                     0x9F38
#define EMV_TAG_APPL_LABEL               0x50
#define EMV_TAG_APPL_NAME                0x9F12
#define EMV_TAG_APPL_EFFECTIVE           0x5F25
#define EMV_TAG_PIN_TRY_COUNTER          0x9F17
#define EMV_TAG_LOG_ENTRY                0x9F4D
#define EMV_TAG_LOG_FMT                  0x9F4F

#define EMV_TAG_LAST_ONLINE_ATC 0x9F13
#define EMV_TAG_ATC             0x9F36
#define EMV_TAG_LOG_AMOUNT      0x9F02
#define EMV_TAG_LOG_COUNTRY     0x9F1A
#define EMV_TAG_LOG_CURRENCY    0x5F2A
#define EMV_TAG_LOG_DATE        0x9A
#define EMV_TAG_LOG_TIME        0x9F21

#define EMV_TAG_TRACK_1_EQUIV            0x56
#define EMV_TAG_TRACK_2_EQUIV            0x57
#define EMV_TAG_PAN                      0x5A
#define EMV_TAG_AFL                      0x94
#define EMV_TAG_EXP_DATE                 0x5F24
#define EMV_TAG_COUNTRY_CODE             0x5F28
#define EMV_TAG_CURRENCY_CODE            0x9F42
#define EMV_TAG_CARDHOLDER_NAME          0x5F20
#define EMV_TAG_CARDHOLDER_NAME_EXTENDED 0x9F0B
#define EMV_TAG_TRACK_2_DATA             0x9F6B
#define EMV_TAG_GPO_FMT1                 0x80

#define EMV_TAG_RESP_BUF_SIZE        0x6C
#define EMV_TAG_RESP_BYTES_AVAILABLE 0x61

// Not used tags
#define EMV_TAG_FORM_FACTOR       0x9F6E
#define EMV_TAG_APP_TEMPLATE      0x61
#define EMV_TAG_FCI               0xBF0C
#define EMV_TAG_DEPOSIT_LOG_ENTRY 0xDF4D



#endif