version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: /bin/bash

  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: >
      bash -c "
        cmake -B build -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON &&
        cmake --build build &&
        cd build && ctest --output-on-failure
      "

  analysis:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: bash scripts/run-analysis.sh 